package com.activity.mapper;

import com.activity.po.LogMaketEditSpecial;
import com.activity.po.LogMaketEditSpecialExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface LogMaketEditSpecialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    long countByExample(LogMaketEditSpecialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    int deleteByExample(LogMaketEditSpecialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    @Insert({
        "insert into log_maket_edit_special (id, edit_userId, ",
        "edit_user_name, edit_date_time, ",
        "old_word, new_word, ",
        "acti_id, acti_name)",
        "values (#{id,jdbcType=BIGINT}, #{editUserid,jdbcType=VARCHAR}, ",
        "#{editUserName,jdbcType=VARCHAR}, #{editDateTime,jdbcType=TIMESTAMP}, ",
        "#{oldWord,jdbcType=VARCHAR}, #{newWord,jdbcType=VARCHAR}, ",
        "#{actiId,jdbcType=BIGINT}, #{actiName,jdbcType=VARCHAR})"
    })
    int insert(LogMaketEditSpecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    int insertSelective(LogMaketEditSpecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    List<LogMaketEditSpecial> selectByExample(LogMaketEditSpecialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LogMaketEditSpecial record, @Param("example") LogMaketEditSpecialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LogMaketEditSpecial record, @Param("example") LogMaketEditSpecialExample example);
}