package com.activity.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LogMaketEditSpecialExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    public LogMaketEditSpecialExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEditUseridIsNull() {
            addCriterion("edit_userId is null");
            return (Criteria) this;
        }

        public Criteria andEditUseridIsNotNull() {
            addCriterion("edit_userId is not null");
            return (Criteria) this;
        }

        public Criteria andEditUseridEqualTo(String value) {
            addCriterion("edit_userId =", value, "editUserid");
            return (Criteria) this;
        }

        public Criteria andEditUseridNotEqualTo(String value) {
            addCriterion("edit_userId <>", value, "editUserid");
            return (Criteria) this;
        }

        public Criteria andEditUseridGreaterThan(String value) {
            addCriterion("edit_userId >", value, "editUserid");
            return (Criteria) this;
        }

        public Criteria andEditUseridGreaterThanOrEqualTo(String value) {
            addCriterion("edit_userId >=", value, "editUserid");
            return (Criteria) this;
        }

        public Criteria andEditUseridLessThan(String value) {
            addCriterion("edit_userId <", value, "editUserid");
            return (Criteria) this;
        }

        public Criteria andEditUseridLessThanOrEqualTo(String value) {
            addCriterion("edit_userId <=", value, "editUserid");
            return (Criteria) this;
        }

        public Criteria andEditUseridLike(String value) {
            addCriterion("edit_userId like", value, "editUserid");
            return (Criteria) this;
        }

        public Criteria andEditUseridNotLike(String value) {
            addCriterion("edit_userId not like", value, "editUserid");
            return (Criteria) this;
        }

        public Criteria andEditUseridIn(List<String> values) {
            addCriterion("edit_userId in", values, "editUserid");
            return (Criteria) this;
        }

        public Criteria andEditUseridNotIn(List<String> values) {
            addCriterion("edit_userId not in", values, "editUserid");
            return (Criteria) this;
        }

        public Criteria andEditUseridBetween(String value1, String value2) {
            addCriterion("edit_userId between", value1, value2, "editUserid");
            return (Criteria) this;
        }

        public Criteria andEditUseridNotBetween(String value1, String value2) {
            addCriterion("edit_userId not between", value1, value2, "editUserid");
            return (Criteria) this;
        }

        public Criteria andEditUserNameIsNull() {
            addCriterion("edit_user_name is null");
            return (Criteria) this;
        }

        public Criteria andEditUserNameIsNotNull() {
            addCriterion("edit_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andEditUserNameEqualTo(String value) {
            addCriterion("edit_user_name =", value, "editUserName");
            return (Criteria) this;
        }

        public Criteria andEditUserNameNotEqualTo(String value) {
            addCriterion("edit_user_name <>", value, "editUserName");
            return (Criteria) this;
        }

        public Criteria andEditUserNameGreaterThan(String value) {
            addCriterion("edit_user_name >", value, "editUserName");
            return (Criteria) this;
        }

        public Criteria andEditUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("edit_user_name >=", value, "editUserName");
            return (Criteria) this;
        }

        public Criteria andEditUserNameLessThan(String value) {
            addCriterion("edit_user_name <", value, "editUserName");
            return (Criteria) this;
        }

        public Criteria andEditUserNameLessThanOrEqualTo(String value) {
            addCriterion("edit_user_name <=", value, "editUserName");
            return (Criteria) this;
        }

        public Criteria andEditUserNameLike(String value) {
            addCriterion("edit_user_name like", value, "editUserName");
            return (Criteria) this;
        }

        public Criteria andEditUserNameNotLike(String value) {
            addCriterion("edit_user_name not like", value, "editUserName");
            return (Criteria) this;
        }

        public Criteria andEditUserNameIn(List<String> values) {
            addCriterion("edit_user_name in", values, "editUserName");
            return (Criteria) this;
        }

        public Criteria andEditUserNameNotIn(List<String> values) {
            addCriterion("edit_user_name not in", values, "editUserName");
            return (Criteria) this;
        }

        public Criteria andEditUserNameBetween(String value1, String value2) {
            addCriterion("edit_user_name between", value1, value2, "editUserName");
            return (Criteria) this;
        }

        public Criteria andEditUserNameNotBetween(String value1, String value2) {
            addCriterion("edit_user_name not between", value1, value2, "editUserName");
            return (Criteria) this;
        }

        public Criteria andEditDateTimeIsNull() {
            addCriterion("edit_date_time is null");
            return (Criteria) this;
        }

        public Criteria andEditDateTimeIsNotNull() {
            addCriterion("edit_date_time is not null");
            return (Criteria) this;
        }

        public Criteria andEditDateTimeEqualTo(Date value) {
            addCriterion("edit_date_time =", value, "editDateTime");
            return (Criteria) this;
        }

        public Criteria andEditDateTimeNotEqualTo(Date value) {
            addCriterion("edit_date_time <>", value, "editDateTime");
            return (Criteria) this;
        }

        public Criteria andEditDateTimeGreaterThan(Date value) {
            addCriterion("edit_date_time >", value, "editDateTime");
            return (Criteria) this;
        }

        public Criteria andEditDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("edit_date_time >=", value, "editDateTime");
            return (Criteria) this;
        }

        public Criteria andEditDateTimeLessThan(Date value) {
            addCriterion("edit_date_time <", value, "editDateTime");
            return (Criteria) this;
        }

        public Criteria andEditDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("edit_date_time <=", value, "editDateTime");
            return (Criteria) this;
        }

        public Criteria andEditDateTimeIn(List<Date> values) {
            addCriterion("edit_date_time in", values, "editDateTime");
            return (Criteria) this;
        }

        public Criteria andEditDateTimeNotIn(List<Date> values) {
            addCriterion("edit_date_time not in", values, "editDateTime");
            return (Criteria) this;
        }

        public Criteria andEditDateTimeBetween(Date value1, Date value2) {
            addCriterion("edit_date_time between", value1, value2, "editDateTime");
            return (Criteria) this;
        }

        public Criteria andEditDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("edit_date_time not between", value1, value2, "editDateTime");
            return (Criteria) this;
        }

        public Criteria andOldWordIsNull() {
            addCriterion("old_word is null");
            return (Criteria) this;
        }

        public Criteria andOldWordIsNotNull() {
            addCriterion("old_word is not null");
            return (Criteria) this;
        }

        public Criteria andOldWordEqualTo(String value) {
            addCriterion("old_word =", value, "oldWord");
            return (Criteria) this;
        }

        public Criteria andOldWordNotEqualTo(String value) {
            addCriterion("old_word <>", value, "oldWord");
            return (Criteria) this;
        }

        public Criteria andOldWordGreaterThan(String value) {
            addCriterion("old_word >", value, "oldWord");
            return (Criteria) this;
        }

        public Criteria andOldWordGreaterThanOrEqualTo(String value) {
            addCriterion("old_word >=", value, "oldWord");
            return (Criteria) this;
        }

        public Criteria andOldWordLessThan(String value) {
            addCriterion("old_word <", value, "oldWord");
            return (Criteria) this;
        }

        public Criteria andOldWordLessThanOrEqualTo(String value) {
            addCriterion("old_word <=", value, "oldWord");
            return (Criteria) this;
        }

        public Criteria andOldWordLike(String value) {
            addCriterion("old_word like", value, "oldWord");
            return (Criteria) this;
        }

        public Criteria andOldWordNotLike(String value) {
            addCriterion("old_word not like", value, "oldWord");
            return (Criteria) this;
        }

        public Criteria andOldWordIn(List<String> values) {
            addCriterion("old_word in", values, "oldWord");
            return (Criteria) this;
        }

        public Criteria andOldWordNotIn(List<String> values) {
            addCriterion("old_word not in", values, "oldWord");
            return (Criteria) this;
        }

        public Criteria andOldWordBetween(String value1, String value2) {
            addCriterion("old_word between", value1, value2, "oldWord");
            return (Criteria) this;
        }

        public Criteria andOldWordNotBetween(String value1, String value2) {
            addCriterion("old_word not between", value1, value2, "oldWord");
            return (Criteria) this;
        }

        public Criteria andNewWordIsNull() {
            addCriterion("new_word is null");
            return (Criteria) this;
        }

        public Criteria andNewWordIsNotNull() {
            addCriterion("new_word is not null");
            return (Criteria) this;
        }

        public Criteria andNewWordEqualTo(String value) {
            addCriterion("new_word =", value, "newWord");
            return (Criteria) this;
        }

        public Criteria andNewWordNotEqualTo(String value) {
            addCriterion("new_word <>", value, "newWord");
            return (Criteria) this;
        }

        public Criteria andNewWordGreaterThan(String value) {
            addCriterion("new_word >", value, "newWord");
            return (Criteria) this;
        }

        public Criteria andNewWordGreaterThanOrEqualTo(String value) {
            addCriterion("new_word >=", value, "newWord");
            return (Criteria) this;
        }

        public Criteria andNewWordLessThan(String value) {
            addCriterion("new_word <", value, "newWord");
            return (Criteria) this;
        }

        public Criteria andNewWordLessThanOrEqualTo(String value) {
            addCriterion("new_word <=", value, "newWord");
            return (Criteria) this;
        }

        public Criteria andNewWordLike(String value) {
            addCriterion("new_word like", value, "newWord");
            return (Criteria) this;
        }

        public Criteria andNewWordNotLike(String value) {
            addCriterion("new_word not like", value, "newWord");
            return (Criteria) this;
        }

        public Criteria andNewWordIn(List<String> values) {
            addCriterion("new_word in", values, "newWord");
            return (Criteria) this;
        }

        public Criteria andNewWordNotIn(List<String> values) {
            addCriterion("new_word not in", values, "newWord");
            return (Criteria) this;
        }

        public Criteria andNewWordBetween(String value1, String value2) {
            addCriterion("new_word between", value1, value2, "newWord");
            return (Criteria) this;
        }

        public Criteria andNewWordNotBetween(String value1, String value2) {
            addCriterion("new_word not between", value1, value2, "newWord");
            return (Criteria) this;
        }

        public Criteria andActiIdIsNull() {
            addCriterion("acti_id is null");
            return (Criteria) this;
        }

        public Criteria andActiIdIsNotNull() {
            addCriterion("acti_id is not null");
            return (Criteria) this;
        }

        public Criteria andActiIdEqualTo(Long value) {
            addCriterion("acti_id =", value, "actiId");
            return (Criteria) this;
        }

        public Criteria andActiIdNotEqualTo(Long value) {
            addCriterion("acti_id <>", value, "actiId");
            return (Criteria) this;
        }

        public Criteria andActiIdGreaterThan(Long value) {
            addCriterion("acti_id >", value, "actiId");
            return (Criteria) this;
        }

        public Criteria andActiIdGreaterThanOrEqualTo(Long value) {
            addCriterion("acti_id >=", value, "actiId");
            return (Criteria) this;
        }

        public Criteria andActiIdLessThan(Long value) {
            addCriterion("acti_id <", value, "actiId");
            return (Criteria) this;
        }

        public Criteria andActiIdLessThanOrEqualTo(Long value) {
            addCriterion("acti_id <=", value, "actiId");
            return (Criteria) this;
        }

        public Criteria andActiIdIn(List<Long> values) {
            addCriterion("acti_id in", values, "actiId");
            return (Criteria) this;
        }

        public Criteria andActiIdNotIn(List<Long> values) {
            addCriterion("acti_id not in", values, "actiId");
            return (Criteria) this;
        }

        public Criteria andActiIdBetween(Long value1, Long value2) {
            addCriterion("acti_id between", value1, value2, "actiId");
            return (Criteria) this;
        }

        public Criteria andActiIdNotBetween(Long value1, Long value2) {
            addCriterion("acti_id not between", value1, value2, "actiId");
            return (Criteria) this;
        }

        public Criteria andActiNameIsNull() {
            addCriterion("acti_name is null");
            return (Criteria) this;
        }

        public Criteria andActiNameIsNotNull() {
            addCriterion("acti_name is not null");
            return (Criteria) this;
        }

        public Criteria andActiNameEqualTo(String value) {
            addCriterion("acti_name =", value, "actiName");
            return (Criteria) this;
        }

        public Criteria andActiNameNotEqualTo(String value) {
            addCriterion("acti_name <>", value, "actiName");
            return (Criteria) this;
        }

        public Criteria andActiNameGreaterThan(String value) {
            addCriterion("acti_name >", value, "actiName");
            return (Criteria) this;
        }

        public Criteria andActiNameGreaterThanOrEqualTo(String value) {
            addCriterion("acti_name >=", value, "actiName");
            return (Criteria) this;
        }

        public Criteria andActiNameLessThan(String value) {
            addCriterion("acti_name <", value, "actiName");
            return (Criteria) this;
        }

        public Criteria andActiNameLessThanOrEqualTo(String value) {
            addCriterion("acti_name <=", value, "actiName");
            return (Criteria) this;
        }

        public Criteria andActiNameLike(String value) {
            addCriterion("acti_name like", value, "actiName");
            return (Criteria) this;
        }

        public Criteria andActiNameNotLike(String value) {
            addCriterion("acti_name not like", value, "actiName");
            return (Criteria) this;
        }

        public Criteria andActiNameIn(List<String> values) {
            addCriterion("acti_name in", values, "actiName");
            return (Criteria) this;
        }

        public Criteria andActiNameNotIn(List<String> values) {
            addCriterion("acti_name not in", values, "actiName");
            return (Criteria) this;
        }

        public Criteria andActiNameBetween(String value1, String value2) {
            addCriterion("acti_name between", value1, value2, "actiName");
            return (Criteria) this;
        }

        public Criteria andActiNameNotBetween(String value1, String value2) {
            addCriterion("acti_name not between", value1, value2, "actiName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}