package com.activity.po;

import com.common.entity.BaseBean;
import java.util.Date;

public class LogMaketEditSpecial extends BaseBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_maket_edit_special.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_maket_edit_special.edit_userId
     *
     * @mbg.generated
     */
    private String editUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_maket_edit_special.edit_user_name
     *
     * @mbg.generated
     */
    private String editUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_maket_edit_special.edit_date_time
     *
     * @mbg.generated
     */
    private Date editDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_maket_edit_special.old_word
     *
     * @mbg.generated
     */
    private String oldWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_maket_edit_special.new_word
     *
     * @mbg.generated
     */
    private String newWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_maket_edit_special.acti_id
     *
     * @mbg.generated
     */
    private Long actiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_maket_edit_special.acti_name
     *
     * @mbg.generated
     */
    private String actiName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_maket_edit_special
     *
     * @mbg.generated
     */
    public LogMaketEditSpecial(Long id, String editUserid, String editUserName, Date editDateTime, String oldWord, String newWord, Long actiId, String actiName) {
        this.id = id;
        this.editUserid = editUserid;
        this.editUserName = editUserName;
        this.editDateTime = editDateTime;
        this.oldWord = oldWord;
        this.newWord = newWord;
        this.actiId = actiId;
        this.actiName = actiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_maket_edit_special.id
     *
     * @return the value of log_maket_edit_special.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_maket_edit_special.edit_userId
     *
     * @return the value of log_maket_edit_special.edit_userId
     *
     * @mbg.generated
     */
    public String getEditUserid() {
        return editUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_maket_edit_special.edit_user_name
     *
     * @return the value of log_maket_edit_special.edit_user_name
     *
     * @mbg.generated
     */
    public String getEditUserName() {
        return editUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_maket_edit_special.edit_date_time
     *
     * @return the value of log_maket_edit_special.edit_date_time
     *
     * @mbg.generated
     */
    public Date getEditDateTime() {
        return editDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_maket_edit_special.old_word
     *
     * @return the value of log_maket_edit_special.old_word
     *
     * @mbg.generated
     */
    public String getOldWord() {
        return oldWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_maket_edit_special.new_word
     *
     * @return the value of log_maket_edit_special.new_word
     *
     * @mbg.generated
     */
    public String getNewWord() {
        return newWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_maket_edit_special.acti_id
     *
     * @return the value of log_maket_edit_special.acti_id
     *
     * @mbg.generated
     */
    public Long getActiId() {
        return actiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_maket_edit_special.acti_name
     *
     * @return the value of log_maket_edit_special.acti_name
     *
     * @mbg.generated
     */
    public String getActiName() {
        return actiName;
    }
}